# Generated by Django 3.2 on 2023-10-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_metodo_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod_producto',
            field=models.CharField(max_length=20, verbose_name='Cod. Producto'),
        ),
    ]
