# Generated by Django 3.2 on 2023-12-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0003_alter_producto_cod_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ordenLinea',
            field=models.CharField(default=0, max_length=10, verbose_name='Orden de Linea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ordenRubro',
            field=models.CharField(default=0, max_length=10, verbose_name='Orden de Rubros'),
            preserve_default=False,
        ),
    ]
