# Generated by Django 3.2 on 2023-07-19 17:57

import Administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocsv',
            name='nombre',
            field=models.CharField(default='None', max_length=128, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='archivocsv',
            name='archivo',
            field=models.FileField(storage=Administrador.models.OverwriteStorage(), upload_to='uploads', verbose_name='Archivo'),
        ),
    ]
