# Generated by Django 3.2 on 2023-07-19 18:41

import Administrador.models
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_auto_20230719_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosDeProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Foto', max_length=100, verbose_name='nombre')),
                ('archivo', models.FileField(default='None', storage=Administrador.models.OverwriteStorage(), upload_to='static/img', verbose_name='Archivo')),
            ],
        ),
        migrations.DeleteModel(
            name='prueba',
        ),
        migrations.AlterField(
            model_name='listadeprecios',
            name='archivo',
            field=models.FileField(default='None', storage=Administrador.models.OverwriteStorage(), upload_to=pathlib.PureWindowsPath('C:/Users/juanm/OneDrive/Escritorio/grupo 2/grupo2-django/uploads'), verbose_name='Archivo'),
        ),
    ]
