# Generated by Django 3.2 on 2023-07-19 18:55

import Administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0004_auto_20230719_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosdeproductos',
            name='archivo',
            field=models.FileField(default='None', storage=Administrador.models.OverwriteStorage(), upload_to='uploads', verbose_name='Archivo'),
        ),
    ]
