# Generated by Django 3.2 on 2023-07-19 19:06

import Administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0005_alter_fotosdeproductos_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosdeproductos',
            name='archivo',
            field=models.ImageField(default='None', storage=Administrador.models.OverwriteStorage(), upload_to='img', verbose_name='Archivo'),
        ),
    ]
