# Generated by Django 3.2 on 2023-07-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0007_alter_fotosdeproductos_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotosdeproductos',
            name='archivo',
            field=models.ImageField(upload_to='img'),
        ),
    ]
