# Generated by Django 3.2 on 2023-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0008_alter_fotosdeproductos_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotosdeproductos',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='fotosdeproductos',
            name='archivo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
