# Generated by Django 3.2 on 2023-07-21 21:56

import Administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0009_auto_20230719_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivocsv',
            name='archivo',
            field=models.FileField(storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='fotosdeproductos',
            name='archivo',
            field=models.ImageField(help_text='Ejemplo: 111111.jpg', null=True, storage=Administrador.models.OverwriteStorage(), upload_to='img'),
        ),
        migrations.AlterField(
            model_name='listadeprecios',
            name='archivo',
            field=models.FileField(default='None', storage=Administrador.models.OverwriteStorage(), upload_to='uploads', verbose_name='Archivo'),
        ),
    ]
