# Generated by Django 3.2 on 2023-07-21 21:59

import Administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0010_auto_20230721_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivocsv',
            name='archivo',
            field=models.FileField(storage=Administrador.models.OverwriteStorage(), upload_to='uploads', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='listadeprecios',
            name='archivo',
            field=models.FileField(default='None', storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path, verbose_name='Archivo'),
        ),
    ]
