# Generated by Django 3.2 on 2023-07-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0011_auto_20230721_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivocsv',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='listadeprecios',
            name='nombre',
        ),
    ]
