# Generated by Django 3.2 on 2023-07-22 17:41

import Administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0012_auto_20230721_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivocsv',
            name='archivo',
            field=models.FileField(storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path_CSV, verbose_name='Archivo'),
        ),
    ]
