# Generated by Django 3.2 on 2023-10-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0015_pedidopormail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrioritariaDeLineas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=500, verbose_name='Lista')),
            ],
        ),
    ]
