# Generated by Django 3.2 on 2023-12-12 20:18

import Administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0016_listaprioritariadelineas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidopormail',
            name='archivo',
            field=models.FileField(help_text='Archivo .pdf del catalogo', storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path_PedidoPorMail, verbose_name='Archivo'),
        ),
    ]
