# Generated by Django 3.2 on 2024-09-01 19:30

import Administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0018_catalogosanitarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo .pdf del catalogo de Gas', storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path_CatalogoGas, verbose_name='Gas')),
            ],
        ),
    ]
