# Generated by Django 3.2 on 2024-09-01 20:07

import Administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0019_catalogogas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoBronce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo .pdf del catalogo de Bronce Roscado', storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path_CatalogoBronce, verbose_name='Bronce')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoEpoxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo .pdf del catalogo de Epoxi', storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path_CatalogoEpoxi, verbose_name='Epoxi')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoFerreteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo .pdf del catalogo de Ferreteria', storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path_CatalogoFerreteria, verbose_name='Ferreteria')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoPPN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo .pdf del catalogo de PPN Espiga', storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path_CatalogoPPN, verbose_name='PPN')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoSigas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo .pdf del catalogo de Sigas', storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path_CatalogoSigas, verbose_name='Sigas')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoThermofusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo .pdf del catalogo de Thermofusion', storage=Administrador.models.OverwriteStorage(), upload_to=Administrador.models.user_directory_path_CatalogoThermofusion, verbose_name='Thermofusion')),
            ],
        ),
    ]
